### ISSUE TITLE
Multimodal3DIdent dataset

### ISSUE THREAD

**Issue by GongxuLuo** [imantdaunhawer/multimodal-contrastive-learning#1]
Hi, could you share the code about how to generate the Multimodal3DIdent dataset. Thanks

**Comment by imantdaunhawer** [comment]
Hey, thanks for reaching out.

As described in the README, the code to generate the Multimodal3DIdent dataset is provided in a separate repo: 
https://github.com/imantdaunhawer/Multimodal3DIdent

Please note that you can also download the dataset directly from Zenodo:
https://zenodo.org/records/7678231
